services:
  backend:
    image: "sematic-search-backend:latest"
    restart: always
    build:
      context: .
    command: ["python", "main.py"]
    ports:
      - "9000:9000"
    networks:
      - app-network

  frontend:
    image: "sematic-search-frontend:latest"
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:9000
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
